In [1]:
# required imports

import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from numpy import savetxt

In [2]:
animals = pd.read_csv("/home/tejsax/Downloads/zoo.data")
df = animals.copy()
animals

animalname  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   
101  kingfisher     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   
101        0         1         1         0     0     2     1         0   

     catsize  type  
0          1     1  
1          1     1  
2          0     4  
3          1     1  
4          1     1  
..       ...   ...  
97         0     6  
98         1     1  
99         0     7  
100        0     2  
101        0     2  

[102 rows x 18 columns]

In [3]:
df.drop(["animalname"], axis=1, inplace=True)
df

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   
101     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  
101         1         1         0     0     2     1         0        0     2  

[102 rows x 17 columns]

In [4]:
x = df.drop(["type"], axis=1)
x

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   
101     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     0         0        1  
1           1         1         0     0     4     1         0        1  
2           1         0         0     1     0     1         0        0  
3           1         1         0     0     4     0         0        1  
4           1         1         0     0     4     1         0        1  
..        ...       ...       ...   ...   ...   ...       ...      ...  
97          0         1         1     0     6     0         0        0  
98          1         1         0     0     4     1         0        1  
99          0         1         0     0     0     0         0        0  
100         1         1         0     0     2     1         0        0  
101         1         1         0     0     2     1         0        0  

[102 rows x 16 columns]

In [5]:
y = df["type"]
y

0      1
1      1
2      4
3      1
4      1
      ..
97     6
98     1
99     7
100    2
101    2
Name: type, Length: 102, dtype: int64

In [6]:
# training

x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, random_state=0)

In [21]:
alg1 = DecisionTreeClassifier()
alg1.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [22]:
y_pred = alg1.predict(x_test)
y_pred

array([5, 4, 4, 1, 3, 1, 2, 1, 1, 1, 7, 1, 4, 7, 4, 6, 1, 6, 2, 4, 2, 3,
       1, 2, 1, 1])

In [23]:
y_pred_train = alg1.predict(x_train)
y_pred_train

array([1, 2, 4, 3, 4, 2, 5, 3, 6, 1, 4, 2, 1, 1, 1, 4, 6, 2, 1, 7, 1, 6,
       4, 1, 1, 2, 1, 4, 1, 1, 2, 1, 2, 5, 1, 1, 6, 1, 2, 2, 4, 1, 7, 7,
       2, 1, 1, 1, 7, 2, 1, 2, 1, 7, 7, 5, 2, 7, 7, 6, 1, 2, 4, 3, 6, 1,
       2, 1, 2, 2, 1, 1, 1, 1, 1, 1])

In [24]:
confusion_matrix(y_train, y_pred_train)

array([[31,  0,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  8]])

In [25]:
confusion_matrix(y_test, y_pred)

array([[10,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  2]])